[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Tekilp"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.0",
    "python-dotenv>=1.1.0",
    "timer>=0.3.0",
]
[tool.replit]
run = "python3 bot.py"
