name: Keep Render Service Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # toutes les 5 minutes UTC

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: curl -fsS https://lre-pomobot.onrender.com/ || true
