name: Keep Render Service Alive

on:
  workflow_dispatch:    # bouton “Run workflow”
  schedule:
    - cron: '*/10 * * * *'   # toutes les 5 minutes UTC

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: |
          echo "⏱️ Pinging at $(date)"
          curl --retry 5 --retry-delay 10 --retry-connrefused -fSs https://lre-pomobot.onrender.com/ || true
